version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/home/node/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # command: sh -c "npm run dev"
    tty: true
    stdin_open: true
